game.resources = [
    
    {name: "prince", type:"image", src: "data/img/prince.png"},
    {name: "sward", type:"image", src: "data/img/sward.png"},
    {name: "letterBlock", type:"image", src: "data/img/letter.png"},
    {name: "logo", type:"image", src: "data/img/logo.png"},
    {name: "deck", type:"image", src: "data/img/deck.png"},
    {name: "gameover", type:"image", src: "data/img/gameover.png"},
    {name: "gameoverbg", type:"image", src: "data/img/gameoverbg.png"},
    {name: "hit", type:"image", src: "data/img/hit.png"},
    {name: "getready", type:"image", src: "data/img/getready.png"},
    {name: "new", type:"image", src: "data/img/new.png"},
    {name: "share", type:"image", src: "data/img/share.png"},
    {name: "tweet", type:"image", src: "data/img/tweet.png"},

    { name: "helper", type: "image", src: "data/img/helper.png" },
    { name: "dude01", type: "image", src: "data/img/dude01.png" },
    { name: "dude02", type: "image", src: "data/img/dude02.png" },
    { name: "dude03", type: "image", src: "data/img/dude03.png" },
    //{ name: "bloodsplat", type: "image", src: "data/img/bloodsplat.png" },
    { name: "heart", type: "image", src: "data/img/heart.png" },
    { name: "burned", type: "image", src: "data/img/burned.png" },
    { name: "lazer", type: "image", src: "data/img/lazer.png" },
    { name: "jump", type: "image", src: "data/img/jump.png" },
    { name: "splash", type: "image", src: "data/img/splash.png" },
    { name: "splash_cta", type: "image", src: "data/img/splash_cta.png" },
    { name: "splash_title", type: "image", src: "data/img/splash_title.png" },
    { name: "end_background", type: "image", src: "data/img/end_background.png" },
    { name: "end_great", type: "image", src: "data/end_great.png" },
    { name: "end_terrible", type: "image", src: "data/end_terrible.png" },
    //{ name: "area01_level_tiles", type: "image", src: "data/area01_level_tiles.png" },
    //{ name: "area02_level_tiles", type: "image", src: "data/area02_level_tiles.png" },
    //{ name: "area03_level_tiles", type: "image", src: "data/area03_level_tiles.png" },
    { name: "16x16_font", type: "image", src: "data/16x16_font.png" },
    { name: "32x32_font", type: "image", src: "data/32x32_font.png" },
    { name: "64x64_font", type: "image", src: "data/64x64_font.png" },
    { name: "hud_hp", type: "image", src: "data/hud_hp.png" },
    { name: "hud_lives", type: "image", src: "data/hud_lives.png" },


    
    {name: "theme", type: "audio", src: "data/bgm/"},
    {name: "hit", type: "audio", src: "data/sfx/"},
    {name: "lose", type: "audio", src: "data/sfx/"},
    {name: "jump", type: "audio", src: "data/sfx/"},


    { name: "bg1", type: "image", src: "data/bg1.png" },
    { name: "bg2", type: "image", src: "data/bg2.png" },
    { name: "bg3", type: "image", src: "data/bg3.png" },
    { name: "mapshit1", type: "image", src: "data/mapshit1.png" },
    { name: "mapshit2", type: "image", src: "data/mapshit2.png" },
    
    { name: "intro", type: "image", src: "data/intro.png" },
    { name: "introcta", type: "image", src: "data/introcta.png" },
    { name: "gameover", type: "image", src: "data/gameover.png" },
    { name: "gameover_good", type: "image", src: "data/gameover_good.png" },
    
    { name: "testlevel", type: "tmx", src: "data/testlevel.tmx"     },
    { name: "gravity",   type: "tmx", src: "data/gravity_level.tmx" },
    { name: "level1",    type: "tmx", src: "data/level1.tmx"        },
    { name: "level2",    type: "tmx", src: "data/level2.tmx"        },
    { name: "level3",    type: "tmx", src: "data/level3.tmx"        }

     _Audio( "death" ),
    _Audio( "doublejump" ),
    _Audio( "enemydeath1" ),
    _Audio( "enemydeath2" ),
    _Audio( "enemydeath3" ),
    _Audio( "enemydeath4" ),
    _Audio( "enemyshoot" ),
    _Audio( "hit" ),
    _Audio( "jump" ),
    _Audio( "ld30-real" ),
    _Audio( "ld30-spirit" ),
    _Audio( "ld30-title" ),
    _Audio( "lostsouls" ),
    _Audio( "pickup" ),
    _Audio( "portal" ),
    _Audio( "portalrev" ),
    _Audio( "radmarslogo" ),
    _Audio( "shoot" )

     { name: "16x16_font", type: "image", src: "data/16x16_font.png" },
    { name: "32x32_font", type: "image", src: "data/32x32_font.png" },
    { name: "64x64_font", type: "image", src: "data/64x64_font.png" },
    { name: "hud_hp", type: "image", src: "data/hud_hp.png" },
    { name: "hud_lives", type: "image", src: "data/hud_lives.png" },


    
    {name: "theme", type: "audio", src: "data/bgm/"},
    {name: "hit", type: "audio", src: "data/sfx/"},
    {name: "lose", type: "audio", src: "data/sfx/"},
    {name: "jump", type: "audio", src: "data/sfx/"},


    { name: "bg1", type: "image", src: "data/bg1.png" },
    { name: "bg2", type: "image", src: "data/bg2.png" },
    { name: "bg3", type: "image", src: "data/bg3.png" },
    { name: "mapshit1", type: "image", src: "data/mapshit1.png" },
    { name: "mapshit2", type: "image", src: "data/mapshit2.png" },
    
    { name: "intro", type: "image", src: "data/intro.png" },
    { name: "introcta", type: "image", src: "data/introcta.png" },
    { name: "gameover", type: "image", src: "data/gameover.png" },
    { name: "gameover_good", type: "image", src: "data/gameover_good.png" },
    
    { name: "testlevel", type: "tmx", src: "data/testlevel.tmx"     },
    { name: "gravity",   type: "tmx", src: "data/gravity_level.tmx" },
    { name: "level1",    type: "tmx", src: "data/level1.tmx"        },
    { name: "level2",    type: "tmx", src: "data/level2.tmx"        },
    { name: "level3",    type: "tmx", src: "data/level3.tmx"        }
    { name: "helper", type: "image", src: "data/img/helper.png" },
    { name: "dude01", type: "image", src: "data/img/dude01.png" },
    { name: "dude02", type: "image", src: "data/img/dude02.png" },
    { name: "dude03", type: "image", src: "data/img/dude03.png" },
    //{ name: "bloodsplat", type: "image", src: "data/img/bloodsplat.png" },
    { name: "heart", type: "image", src: "data/img/heart.png" },
    { name: "burned", type: "image", src: "data/img/burned.png" },
    { name: "lazer", type: "image", src: "data/img/lazer.png" },
    { name: "jump", type: "image", src: "data/img/jump.png" },
    { name: "splash", type: "image", src: "data/img/splash.png" },
    { name: "splash_cta", type: "image", src: "data/img/splash_cta.png" },
    { name: "splash_title", type: "image", src: "data/img/splash_title.png" },
    { name: "end_background", type: "image", src: "data/img/end_background.png" },
    { name: "end_great", type: "image", src: "data/end_great.png" },
    { name: "end_terrible", type: "image", src: "data/end_terrible.png" },
     {name: "prince", type:"image", src: "data/img/prince.png"},
    {name: "sward", type:"image", src: "data/img/sward.png"},
    {name: "letterBlock", type:"image", src: "data/img/letter.png"},
    {name: "logo", type:"image", src: "data/img/logo.png"},
    {name: "deck", type:"image", src: "data/img/deck.png"},
    {name: "gameover", type:"image", src: "data/img/gameover.png"},
    {name: "gameoverbg", type:"image", src: "data/img/gameoverbg.png"},
    {name: "hit", type:"image", src: "data/img/hit.png"},
    {name: "getready", type:"image", src: "data/img/getready.png"},
    {name: "new", type:"image", src: "data/img/new.png"},
    {name: "share", type:"image", src: "data/img/share.png"},
    {name: "tweet", type:"image", src: "data/img/tweet.png"},

    { name: "helper", type: "image", src: "data/img/helper.png" },
    { name: "dude01", type: "image", src: "data/img/dude01.png" },
    { name: "dude02", type: "image", src: "data/img/dude02.png" },
    { name: "dude03", type: "image", src: "data/img/dude03.png" },
    //{ name: "bloodsplat", type: "image", src: "data/img/bloodsplat.png" },
    { name: "heart", type: "image", src: "data/img/heart.png" },
    { name: "burned", type: "image", src: "data/img/burned.png" },
    { name: "lazer", type: "image", src: "data/img/lazer.png" },
    { name: "jump", type: "image", src: "data/img/jump.png" },
    { name: "splash", type: "image", src: "data/img/splash.png" },
    { name: "splash_cta", type: "image", src: "data/img/splash_cta.png" },
    { name: "splash_title", type: "image", src: "data/img/splash_title.png" },
    { name: "end_background", type: "image", src: "data/img/end_background.png" },
    { name: "end_great", type: "image", src: "data/end_great.png" },
    { name: "end_terrible", type: "image", src: "data/end_terrible.png" },
    //{ name: "area01_level_tiles", type: "image", src: "data/area01_level_tiles.png" },
    //{ name: "area02_level_tiles", type: "image", src: "data/area02_level_tiles.png" },
    //{ name: "area03_level_tiles", type: "image", src: "data/area03_level_tiles.png" },
    { name: "16x16_font", type: "image", src: "data/16x16_font.png" },
    { name: "32x32_font", type: "image", src: "data/32x32_font.png" },
    { name: "64x64_font", type: "image", src: "data/64x64_font.png" },
    { name: "hud_hp", type: "image", src: "data/hud_hp.png" },
    { name: "hud_lives", type: "image", src: "data/hud_lives.png" },
    {name: "prince", type:"image", src: "data/img/prince.png"},
    {name: "sward", type:"image", src: "data/img/sward.png"},
    {name: "letterBlock", type:"image", src: "data/img/letter.png"},
    {name: "logo", type:"image", src: "data/img/logo.png"},
    {name: "deck", type:"image", src: "data/img/deck.png"},
    {name: "gameover", type:"image", src: "data/img/gameover.png"},
    {name: "gameoverbg", type:"image", src: "data/img/gameoverbg.png"},
    {name: "hit", type:"image", src: "data/img/hit.png"},
    {name: "getready", type:"image", src: "data/img/getready.png"},
    {name: "new", type:"image", src: "data/img/new.png"},
    {name: "share", type:"image", src: "data/img/share.png"},
    {name: "tweet", type:"image", src: "data/img/tweet.png"},

    { name: "helper", type: "image", src: "data/img/helper.png" },
    { name: "dude01", type: "image", src: "data/img/dude01.png" },
    { name: "dude02", type: "image", src: "data/img/dude02.png" },
    { name: "dude03", type: "image", src: "data/img/dude03.png" },
    //{ name: "bloodsplat", type: "image", src: "data/img/bloodsplat.png" },
    { name: "heart", type: "image", src: "data/img/heart.png" },
    { name: "burned", type: "image", src: "data/img/burned.png" },
    { name: "lazer", type: "image", src: "data/img/lazer.png" },
    { name: "jump", type: "image", src: "data/img/jump.png" },
    { name: "splash", type: "image", src: "data/img/splash.png" },
    { name: "splash_cta", type: "image", src: "data/img/splash_cta.png" },
    { name: "splash_title", type: "image", src: "data/img/splash_title.png" },
    { name: "end_background", type: "image", src: "data/img/end_background.png" },
    { name: "end_great", type: "image", src: "data/end_great.png" },
    { name: "end_terrible", type: "image", src: "data/end_terrible.png" },
    //{ name: "area01_level_tiles", type: "image", src: "data/area01_level_tiles.png" },
    //{ name: "area02_level_tiles", type: "image", src: "data/area02_level_tiles.png" },
    //{ name: "area03_level_tiles", type: "image", src: "data/area03_level_tiles.png" },
    { name: "16x16_font", type: "image", src: "data/16x16_font.png" },
    { name: "32x32_font", type: "image", src: "data/32x32_font.png" },
    { name: "64x64_font", type: "image", src: "data/64x64_font.png" },
    { name: "hud_hp", type: "image", src: "data/hud_hp.png" },
    { name: "hud_lives", type: "image", src: "data/hud_lives.png" },
    {name: "prince", type:"image", src: "data/img/prince.png"},
    {name: "sward", type:"image", src: "data/img/sward.png"},
    {name: "letterBlock", type:"image", src: "data/img/letter.png"},
    {name: "logo", type:"image", src: "data/img/logo.png"},
    {name: "deck", type:"image", src: "data/img/deck.png"},
    {name: "gameover", type:"image", src: "data/img/gameover.png"},
    {name: "gameoverbg", type:"image", src: "data/img/gameoverbg.png"},
    {name: "hit", type:"image", src: "data/img/hit.png"},
    {name: "getready", type:"image", src: "data/img/getready.png"},
    {name: "new", type:"image", src: "data/img/new.png"},
    {name: "share", type:"image", src: "data/img/share.png"},
    {name: "tweet", type:"image", src: "data/img/tweet.png"},

    { name: "helper", type: "image", src: "data/img/helper.png" },
    { name: "dude01", type: "image", src: "data/img/dude01.png" },
    { name: "dude02", type: "image", src: "data/img/dude02.png" },
    { name: "dude03", type: "image", src: "data/img/dude03.png" },
    //{ name: "bloodsplat", type: "image", src: "data/img/bloodsplat.png" },
    { name: "heart", type: "image", src: "data/img/heart.png" },
    { name: "burned", type: "image", src: "data/img/burned.png" },
    { name: "lazer", type: "image", src: "data/img/lazer.png" },
    { name: "jump", type: "image", src: "data/img/jump.png" },
    { name: "splash", type: "image", src: "data/img/splash.png" },
    { name: "splash_cta", type: "image", src: "data/img/splash_cta.png" },
    { name: "splash_title", type: "image", src: "data/img/splash_title.png" },
    { name: "end_background", type: "image", src: "data/img/end_background.png" },
    { name: "end_great", type: "image", src: "data/end_great.png" },
    { name: "end_terrible", type: "image", src: "data/end_terrible.png" },
    //{ name: "area01_level_tiles", type: "image", src: "data/area01_level_tiles.png" },
    //{ name: "area02_level_tiles", type: "image", src: "data/area02_level_tiles.png" },
    //{ name: "area03_level_tiles", type: "image", src: "data/area03_level_tiles.png" },
    { name: "16x16_font", type: "image", src: "data/16x16_font.png" },
    { name: "32x32_font", type: "image", src: "data/32x32_font.png" },
    { name: "64x64_font", type: "image", src: "data/64x64_font.png" },
    { name: "hud_hp", type: "image", src: "data/hud_hp.png" },
    { name: "hud_lives", type: "image", src: "data/hud_lives.png" },


];